/**
 * Machine-readable clickability matrix — device remediation (code audit).
 * Status: code_ok | unavailable_explained | blocked_owner_rpc | fail | pending_device
 * Device column filled after S25 manual pass.
 */

export type ClickabilityRow = {
  id: string;
  role: string;
  screen: string;
  element: string;
  hasHandler: boolean;
  routeOrAction: string;
  status: 'code_ok' | 'unavailable_explained' | 'blocked_owner_rpc' | 'fail' | 'pending_device';
  notes: string;
};

export const clickabilityMatrix: ClickabilityRow[] = [
  {
    id: 'admin-tab-home',
    role: 'admin',
    screen: 'tabbar',
    element: 'Home tab',
    hasHandler: true,
    routeOrAction: '/(admin)/',
    status: 'blocked_owner_rpc',
    notes: 'Tab navigates; Home loader fails closed on admin_dashboard_stats/admin_work_queue',
  },
  {
    id: 'admin-tab-approvals',
    role: 'admin',
    screen: 'tabbar',
    element: 'Goedkeuringen tab',
    hasHandler: true,
    routeOrAction: '/(admin)/approvals',
    status: 'blocked_owner_rpc',
    notes: 'Depends on admin_work_queue',
  },
  {
    id: 'admin-tab-tickets',
    role: 'admin',
    screen: 'tabbar',
    element: 'Tickets tab',
    hasHandler: true,
    routeOrAction: '/(admin)/tickets',
    status: 'code_ok',
    notes: 'listAdminTickets → portal_support_tickets via contract table',
  },
  {
    id: 'admin-tab-finance',
    role: 'admin',
    screen: 'tabbar',
    element: 'Financiën tab',
    hasHandler: true,
    routeOrAction: '/(admin)/finance',
    status: 'code_ok',
    notes: 'List via partner_commissions / payout requests; mutations show unavailable',
  },
  {
    id: 'admin-tab-more',
    role: 'admin',
    screen: 'tabbar',
    element: 'Meer tab',
    hasHandler: true,
    routeOrAction: '/(admin)/more',
    status: 'code_ok',
    notes: 'Max 5 primary tabs; leads href null',
  },
  {
    id: 'admin-tab-leads-hidden',
    role: 'admin',
    screen: 'tabbar',
    element: 'leads primary tab',
    hasHandler: false,
    routeOrAction: 'href:null',
    status: 'code_ok',
    notes: 'Must not appear as 6th tab',
  },
  {
    id: 'admin-more-leads',
    role: 'admin',
    screen: 'Meer',
    element: 'Partnerleads',
    hasHandler: true,
    routeOrAction: '/(admin)/leads',
    status: 'code_ok',
    notes: 'partner_leads table read + review RPCs',
  },
  {
    id: 'admin-more-products',
    role: 'admin',
    screen: 'Meer',
    element: 'Producten',
    hasHandler: true,
    routeOrAction: '/(admin)/more/surface/products',
    status: 'unavailable_explained',
    notes: 'Nog niet beschikbaar until Owner RPC/handoff',
  },
  {
    id: 'admin-more-partners',
    role: 'admin',
    screen: 'Meer',
    element: 'Partners',
    hasHandler: true,
    routeOrAction: '/(admin)/more/surface/partners',
    status: 'unavailable_explained',
    notes: 'Await suspend/reactivate + list RPCs',
  },
  {
    id: 'admin-more-customers',
    role: 'admin',
    screen: 'Meer',
    element: 'Klanten',
    hasHandler: true,
    routeOrAction: '/(admin)/more/surface/customers',
    status: 'unavailable_explained',
    notes: 'Owner list RPC required',
  },
  {
    id: 'admin-more-projects',
    role: 'admin',
    screen: 'Meer',
    element: 'Projecten',
    hasHandler: true,
    routeOrAction: '/(admin)/more/surface/projects',
    status: 'unavailable_explained',
    notes: 'Admin portal_projects list surface TBD',
  },
  {
    id: 'admin-more-quotes',
    role: 'admin',
    screen: 'Meer',
    element: 'Offertes',
    hasHandler: true,
    routeOrAction: '/(admin)/more/surface/quotes',
    status: 'unavailable_explained',
    notes: 'Admin portal_quotes list surface TBD',
  },
  {
    id: 'admin-more-invoices',
    role: 'admin',
    screen: 'Meer',
    element: 'Facturen',
    hasHandler: true,
    routeOrAction: '/(admin)/more/surface/invoices',
    status: 'unavailable_explained',
    notes: 'Admin portal_invoices list surface TBD',
  },
  {
    id: 'admin-more-appointments',
    role: 'admin',
    screen: 'Meer',
    element: 'Afspraken',
    hasHandler: true,
    routeOrAction: '/(admin)/more/surface/appointments',
    status: 'unavailable_explained',
    notes: 'Admin appointments list surface TBD',
  },
  {
    id: 'admin-more-settings',
    role: 'admin',
    screen: 'Meer',
    element: 'Instellingen',
    hasHandler: true,
    routeOrAction: '/(admin)/more/surface/settings',
    status: 'unavailable_explained',
    notes: 'Placeholder until settings contract',
  },
  {
    id: 'admin-more-whatsapp',
    role: 'admin',
    screen: 'Meer',
    element: 'WhatsApp',
    hasHandler: true,
    routeOrAction: 'wa.me/31628600727',
    status: 'code_ok',
    notes: 'Central config; no PII in URL',
  },
  {
    id: 'admin-more-security',
    role: 'admin',
    screen: 'Meer',
    element: 'Beveiliging',
    hasHandler: true,
    routeOrAction: '/(admin)/more/surface/security',
    status: 'unavailable_explained',
    notes: 'AAL2/security status Owner surface TBD',
  },
  {
    id: 'admin-more-logout',
    role: 'admin',
    screen: 'Meer',
    element: 'Uitloggen',
    hasHandler: true,
    routeOrAction: 'signOut → /(public)',
    status: 'code_ok',
    notes: '',
  },
  {
    id: 'admin-home-retry',
    role: 'admin',
    screen: 'Home',
    element: 'Opnieuw proberen',
    hasHandler: true,
    routeOrAction: 'reload getAdminDashboardBundle',
    status: 'blocked_owner_rpc',
    notes: 'Retry cannot succeed until Owner RPCs land',
  },
  {
    id: 'admin-finance-commission-actions',
    role: 'admin',
    screen: 'Financiën',
    element: 'Commission approve/reject',
    hasHandler: false,
    routeOrAction: 'unavailable copy',
    status: 'unavailable_explained',
    notes: 'approve_commission / reject_commission not in contract',
  },
  {
    id: 'admin-finance-payout-process',
    role: 'admin',
    screen: 'Financiën',
    element: 'Process payout',
    hasHandler: false,
    routeOrAction: 'disabled by Owner decision',
    status: 'unavailable_explained',
    notes: 'Payout processing stays off until separate auth',
  },
  {
    id: 'customer-more-whatsapp',
    role: 'customer',
    screen: 'Meer',
    element: 'WhatsApp',
    hasHandler: true,
    routeOrAction: 'wa.me/31628600727',
    status: 'code_ok',
    notes: 'No profile name in message',
  },
  {
    id: 'partner-more-whatsapp',
    role: 'partner',
    screen: 'Meer',
    element: 'WhatsApp',
    hasHandler: true,
    routeOrAction: 'wa.me/31628600727',
    status: 'code_ok',
    notes: '',
  },
  {
    id: 'partner-more-payout',
    role: 'partner',
    screen: 'Meer',
    element: 'Request payout',
    hasHandler: false,
    routeOrAction: 'feature flag partnerPayouts',
    status: 'unavailable_explained',
    notes: 'No onPress when flag false — subtitle payoutDisabled',
  },
];
