/**
 * AUTO-GENERATED by scripts/gen-db-types.mjs — do not edit by hand.
 * Source: local Mobile Supabase schema (127.0.0.1:54522, project vdb-digital-mobile-local)
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      account_deletion_requests: {
        Row: {
          created_at: string
          id: string
          notes: string | null
          processed_at: string | null
          processed_by: string | null
          reason: string | null
          requested_at: string
          status: Database["public"]["Enums"]["account_deletion_status"]
          updated_at: string
          user_id: string
          verified_at: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          notes?: string | null
          processed_at?: string | null
          processed_by?: string | null
          reason?: string | null
          requested_at?: string
          status?: Database["public"]["Enums"]["account_deletion_status"]
          updated_at?: string
          user_id: string
          verified_at?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          notes?: string | null
          processed_at?: string | null
          processed_by?: string | null
          reason?: string | null
          requested_at?: string
          status?: Database["public"]["Enums"]["account_deletion_status"]
          updated_at?: string
          user_id?: string
          verified_at?: string | null
        }
        Relationships: []
      }
      app_profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          email: string | null
          full_name: string | null
          id: string
          locale: string
          phone: string | null
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id: string
          locale?: string
          phone?: string | null
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id?: string
          locale?: string
          phone?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      appointments: {
        Row: {
          cancellation_reason: string | null
          cancelled_at: string | null
          created_at: string
          customer_user_id: string
          ends_at: string
          id: string
          location: string | null
          meeting_url: string | null
          notes: string | null
          project_id: string | null
          slot_id: string | null
          staff_user_id: string | null
          starts_at: string
          status: Database["public"]["Enums"]["appointment_status"]
          timezone: string
          updated_at: string
        }
        Insert: {
          cancellation_reason?: string | null
          cancelled_at?: string | null
          created_at?: string
          customer_user_id: string
          ends_at: string
          id?: string
          location?: string | null
          meeting_url?: string | null
          notes?: string | null
          project_id?: string | null
          slot_id?: string | null
          staff_user_id?: string | null
          starts_at: string
          status?: Database["public"]["Enums"]["appointment_status"]
          timezone?: string
          updated_at?: string
        }
        Update: {
          cancellation_reason?: string | null
          cancelled_at?: string | null
          created_at?: string
          customer_user_id?: string
          ends_at?: string
          id?: string
          location?: string | null
          meeting_url?: string | null
          notes?: string | null
          project_id?: string | null
          slot_id?: string | null
          staff_user_id?: string | null
          starts_at?: string
          status?: Database["public"]["Enums"]["appointment_status"]
          timezone?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "appointments_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_slot_id_fkey"
            columns: ["slot_id"]
            isOneToOne: false
            referencedRelation: "availability_slots"
            referencedColumns: ["id"]
          },
        ]
      }
      availability_slots: {
        Row: {
          booked_count: number
          capacity: number
          created_at: string
          ends_at: string
          id: string
          is_bookable: boolean
          staff_user_id: string | null
          starts_at: string
          timezone: string
          updated_at: string
        }
        Insert: {
          booked_count?: number
          capacity?: number
          created_at?: string
          ends_at: string
          id?: string
          is_bookable?: boolean
          staff_user_id?: string | null
          starts_at: string
          timezone?: string
          updated_at?: string
        }
        Update: {
          booked_count?: number
          capacity?: number
          created_at?: string
          ends_at?: string
          id?: string
          is_bookable?: boolean
          staff_user_id?: string | null
          starts_at?: string
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
      commission_events: {
        Row: {
          actor_id: string | null
          commission_id: string
          created_at: string
          from_status: Database["public"]["Enums"]["commission_status"] | null
          id: string
          metadata: Json
          reason: string | null
          to_status: Database["public"]["Enums"]["commission_status"]
        }
        Insert: {
          actor_id?: string | null
          commission_id: string
          created_at?: string
          from_status?: Database["public"]["Enums"]["commission_status"] | null
          id?: string
          metadata?: Json
          reason?: string | null
          to_status: Database["public"]["Enums"]["commission_status"]
        }
        Update: {
          actor_id?: string | null
          commission_id?: string
          created_at?: string
          from_status?: Database["public"]["Enums"]["commission_status"] | null
          id?: string
          metadata?: Json
          reason?: string | null
          to_status?: Database["public"]["Enums"]["commission_status"]
        }
        Relationships: [
          {
            foreignKeyName: "commission_events_commission_id_fkey"
            columns: ["commission_id"]
            isOneToOne: false
            referencedRelation: "commissions"
            referencedColumns: ["id"]
          },
        ]
      }
      commissions: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          basis_amount_cents: number
          commission_amount_cents: number
          created_at: string
          currency: string
          fixed_amount_cents: number | null
          hold_until: string | null
          id: string
          metadata: Json
          paid_at: string | null
          partner_id: string
          rate_bps: number | null
          rejection_reason: string | null
          sale_id: string
          status: Database["public"]["Enums"]["commission_status"]
          updated_at: string
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          basis_amount_cents: number
          commission_amount_cents?: number
          created_at?: string
          currency?: string
          fixed_amount_cents?: number | null
          hold_until?: string | null
          id?: string
          metadata?: Json
          paid_at?: string | null
          partner_id: string
          rate_bps?: number | null
          rejection_reason?: string | null
          sale_id: string
          status?: Database["public"]["Enums"]["commission_status"]
          updated_at?: string
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          basis_amount_cents?: number
          commission_amount_cents?: number
          created_at?: string
          currency?: string
          fixed_amount_cents?: number | null
          hold_until?: string | null
          id?: string
          metadata?: Json
          paid_at?: string | null
          partner_id?: string
          rate_bps?: number | null
          rejection_reason?: string | null
          sale_id?: string
          status?: Database["public"]["Enums"]["commission_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "commissions_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partner_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "commissions_sale_id_fkey"
            columns: ["sale_id"]
            isOneToOne: false
            referencedRelation: "sales"
            referencedColumns: ["id"]
          },
        ]
      }
      conversation_participants: {
        Row: {
          conversation_id: string
          created_at: string
          id: string
          joined_at: string
          left_at: string | null
          muted_until: string | null
          role: string
          updated_at: string
          user_id: string
        }
        Insert: {
          conversation_id: string
          created_at?: string
          id?: string
          joined_at?: string
          left_at?: string | null
          muted_until?: string | null
          role?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          conversation_id?: string
          created_at?: string
          id?: string
          joined_at?: string
          left_at?: string | null
          muted_until?: string | null
          role?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversation_participants_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      conversations: {
        Row: {
          archived_at: string | null
          conversation_type: Database["public"]["Enums"]["conversation_type"]
          created_at: string
          created_by: string | null
          id: string
          last_message_at: string | null
          project_id: string | null
          subject: string | null
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          conversation_type?: Database["public"]["Enums"]["conversation_type"]
          created_at?: string
          created_by?: string | null
          id?: string
          last_message_at?: string | null
          project_id?: string | null
          subject?: string | null
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          conversation_type?: Database["public"]["Enums"]["conversation_type"]
          created_at?: string
          created_by?: string | null
          id?: string
          last_message_at?: string | null
          project_id?: string | null
          subject?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversations_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      document_reviews: {
        Row: {
          comment: string | null
          created_at: string
          decision: Database["public"]["Enums"]["document_review_decision"]
          document_id: string
          document_version_id: string
          id: string
          reviewer_id: string
        }
        Insert: {
          comment?: string | null
          created_at?: string
          decision: Database["public"]["Enums"]["document_review_decision"]
          document_id: string
          document_version_id: string
          id?: string
          reviewer_id: string
        }
        Update: {
          comment?: string | null
          created_at?: string
          decision?: Database["public"]["Enums"]["document_review_decision"]
          document_id?: string
          document_version_id?: string
          id?: string
          reviewer_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "document_reviews_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "document_reviews_document_version_id_fkey"
            columns: ["document_version_id"]
            isOneToOne: false
            referencedRelation: "document_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      document_versions: {
        Row: {
          byte_size: number
          checksum_sha256: string | null
          client_upload_id: string | null
          created_at: string
          document_id: string
          id: string
          mime_type: string
          notes: string | null
          scan_status: Database["public"]["Enums"]["document_scan_status"]
          status: Database["public"]["Enums"]["document_status"]
          storage_path: string
          updated_at: string
          uploaded_by: string
          version_number: number
        }
        Insert: {
          byte_size: number
          checksum_sha256?: string | null
          client_upload_id?: string | null
          created_at?: string
          document_id: string
          id?: string
          mime_type: string
          notes?: string | null
          scan_status?: Database["public"]["Enums"]["document_scan_status"]
          status?: Database["public"]["Enums"]["document_status"]
          storage_path: string
          updated_at?: string
          uploaded_by: string
          version_number: number
        }
        Update: {
          byte_size?: number
          checksum_sha256?: string | null
          client_upload_id?: string | null
          created_at?: string
          document_id?: string
          id?: string
          mime_type?: string
          notes?: string | null
          scan_status?: Database["public"]["Enums"]["document_scan_status"]
          status?: Database["public"]["Enums"]["document_status"]
          storage_path?: string
          updated_at?: string
          uploaded_by?: string
          version_number?: number
        }
        Relationships: [
          {
            foreignKeyName: "document_versions_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
        ]
      }
      documents: {
        Row: {
          category: string | null
          created_at: string
          current_version_id: string | null
          deleted_at: string | null
          id: string
          owner_user_id: string
          project_id: string | null
          requires_customer_approval: boolean
          status: Database["public"]["Enums"]["document_status"]
          title: string
          updated_at: string
        }
        Insert: {
          category?: string | null
          created_at?: string
          current_version_id?: string | null
          deleted_at?: string | null
          id?: string
          owner_user_id: string
          project_id?: string | null
          requires_customer_approval?: boolean
          status?: Database["public"]["Enums"]["document_status"]
          title: string
          updated_at?: string
        }
        Update: {
          category?: string | null
          created_at?: string
          current_version_id?: string | null
          deleted_at?: string | null
          id?: string
          owner_user_id?: string
          project_id?: string | null
          requires_customer_approval?: boolean
          status?: Database["public"]["Enums"]["document_status"]
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "documents_current_version_id_fkey"
            columns: ["current_version_id"]
            isOneToOne: false
            referencedRelation: "document_versions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "documents_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      feature_flags: {
        Row: {
          created_at: string
          description: string | null
          enabled: boolean
          id: string
          key: string
          payload: Json
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          enabled?: boolean
          id?: string
          key: string
          payload?: Json
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          enabled?: boolean
          id?: string
          key?: string
          payload?: Json
          updated_at?: string
        }
        Relationships: []
      }
      invoice_items: {
        Row: {
          created_at: string
          description: string
          id: string
          invoice_id: string
          quantity: number
          sort_order: number
          tax_rate_bps: number
          unit_amount_cents: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          description: string
          id?: string
          invoice_id: string
          quantity?: number
          sort_order?: number
          tax_rate_bps?: number
          unit_amount_cents: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string
          id?: string
          invoice_id?: string
          quantity?: number
          sort_order?: number
          tax_rate_bps?: number
          unit_amount_cents?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "invoice_items_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "invoices"
            referencedColumns: ["id"]
          },
        ]
      }
      invoices: {
        Row: {
          amount_paid_cents: number
          created_at: string
          currency: string
          customer_user_id: string
          deleted_at: string | null
          due_on: string | null
          id: string
          invoice_number: string
          issued_on: string | null
          order_id: string | null
          payment_reference: string | null
          pdf_storage_path: string | null
          project_id: string | null
          quote_id: string | null
          status: Database["public"]["Enums"]["invoice_status"]
          subtotal_cents: number
          tax_cents: number
          total_cents: number
          updated_at: string
        }
        Insert: {
          amount_paid_cents?: number
          created_at?: string
          currency?: string
          customer_user_id: string
          deleted_at?: string | null
          due_on?: string | null
          id?: string
          invoice_number: string
          issued_on?: string | null
          order_id?: string | null
          payment_reference?: string | null
          pdf_storage_path?: string | null
          project_id?: string | null
          quote_id?: string | null
          status?: Database["public"]["Enums"]["invoice_status"]
          subtotal_cents?: number
          tax_cents?: number
          total_cents?: number
          updated_at?: string
        }
        Update: {
          amount_paid_cents?: number
          created_at?: string
          currency?: string
          customer_user_id?: string
          deleted_at?: string | null
          due_on?: string | null
          id?: string
          invoice_number?: string
          issued_on?: string | null
          order_id?: string | null
          payment_reference?: string | null
          pdf_storage_path?: string | null
          project_id?: string | null
          quote_id?: string | null
          status?: Database["public"]["Enums"]["invoice_status"]
          subtotal_cents?: number
          tax_cents?: number
          total_cents?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "invoices_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
        ]
      }
      message_receipts: {
        Row: {
          created_at: string
          delivered_at: string | null
          id: string
          message_id: string
          read_at: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          delivered_at?: string | null
          id?: string
          message_id: string
          read_at?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          delivered_at?: string | null
          id?: string
          message_id?: string
          read_at?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "message_receipts_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          attachment_mime: string | null
          attachment_path: string | null
          body: string | null
          client_message_id: string | null
          conversation_id: string
          created_at: string
          deleted_at: string | null
          edited_at: string | null
          id: string
          sender_id: string
          sent_at: string
          updated_at: string
        }
        Insert: {
          attachment_mime?: string | null
          attachment_path?: string | null
          body?: string | null
          client_message_id?: string | null
          conversation_id: string
          created_at?: string
          deleted_at?: string | null
          edited_at?: string | null
          id?: string
          sender_id: string
          sent_at?: string
          updated_at?: string
        }
        Update: {
          attachment_mime?: string | null
          attachment_path?: string | null
          body?: string | null
          client_message_id?: string | null
          conversation_id?: string
          created_at?: string
          deleted_at?: string | null
          edited_at?: string | null
          id?: string
          sender_id?: string
          sent_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_deliveries: {
        Row: {
          attempted_at: string | null
          channel: Database["public"]["Enums"]["notification_channel"]
          created_at: string
          error_message: string | null
          id: string
          notification_id: string
          provider_message_id: string | null
          push_token_id: string | null
          status: Database["public"]["Enums"]["notification_delivery_status"]
          updated_at: string
        }
        Insert: {
          attempted_at?: string | null
          channel: Database["public"]["Enums"]["notification_channel"]
          created_at?: string
          error_message?: string | null
          id?: string
          notification_id: string
          provider_message_id?: string | null
          push_token_id?: string | null
          status?: Database["public"]["Enums"]["notification_delivery_status"]
          updated_at?: string
        }
        Update: {
          attempted_at?: string | null
          channel?: Database["public"]["Enums"]["notification_channel"]
          created_at?: string
          error_message?: string | null
          id?: string
          notification_id?: string
          provider_message_id?: string | null
          push_token_id?: string | null
          status?: Database["public"]["Enums"]["notification_delivery_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "notification_deliveries_notification_id_fkey"
            columns: ["notification_id"]
            isOneToOne: false
            referencedRelation: "notifications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notification_deliveries_push_token_id_fkey"
            columns: ["push_token_id"]
            isOneToOne: false
            referencedRelation: "push_tokens"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string
          category: string | null
          created_at: string
          data: Json
          deep_link: string | null
          id: string
          read_at: string | null
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          body: string
          category?: string | null
          created_at?: string
          data?: Json
          deep_link?: string | null
          id?: string
          read_at?: string | null
          title: string
          updated_at?: string
          user_id: string
        }
        Update: {
          body?: string
          category?: string | null
          created_at?: string
          data?: Json
          deep_link?: string | null
          id?: string
          read_at?: string | null
          title?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      partner_applications: {
        Row: {
          accepted_partner_rules: boolean
          accepted_privacy_policy: boolean
          company_name: string | null
          country: string | null
          created_at: string
          deleted_at: string | null
          email: string
          experience: string | null
          full_name: string
          id: string
          motivation: string | null
          phone: string | null
          review_notes: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          sales_channel: string | null
          status: Database["public"]["Enums"]["partner_application_status"]
          updated_at: string
          user_id: string
        }
        Insert: {
          accepted_partner_rules?: boolean
          accepted_privacy_policy?: boolean
          company_name?: string | null
          country?: string | null
          created_at?: string
          deleted_at?: string | null
          email: string
          experience?: string | null
          full_name: string
          id?: string
          motivation?: string | null
          phone?: string | null
          review_notes?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          sales_channel?: string | null
          status?: Database["public"]["Enums"]["partner_application_status"]
          updated_at?: string
          user_id: string
        }
        Update: {
          accepted_partner_rules?: boolean
          accepted_privacy_policy?: boolean
          company_name?: string | null
          country?: string | null
          created_at?: string
          deleted_at?: string | null
          email?: string
          experience?: string | null
          full_name?: string
          id?: string
          motivation?: string | null
          phone?: string | null
          review_notes?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          sales_channel?: string | null
          status?: Database["public"]["Enums"]["partner_application_status"]
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      partner_codes: {
        Row: {
          campaign: string | null
          code: string
          created_at: string
          expires_at: string | null
          id: string
          is_active: boolean
          max_uses: number | null
          partner_id: string
          updated_at: string
          uses_count: number
        }
        Insert: {
          campaign?: string | null
          code: string
          created_at?: string
          expires_at?: string | null
          id?: string
          is_active?: boolean
          max_uses?: number | null
          partner_id: string
          updated_at?: string
          uses_count?: number
        }
        Update: {
          campaign?: string | null
          code?: string
          created_at?: string
          expires_at?: string | null
          id?: string
          is_active?: boolean
          max_uses?: number | null
          partner_id?: string
          updated_at?: string
          uses_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "partner_codes_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partner_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      partner_lead_staff_notes: {
        Row: {
          created_at: string
          created_by: string
          id: string
          lead_id: string
          note: string
        }
        Insert: {
          created_at?: string
          created_by: string
          id?: string
          lead_id: string
          note: string
        }
        Update: {
          created_at?: string
          created_by?: string
          id?: string
          lead_id?: string
          note?: string
        }
        Relationships: [
          {
            foreignKeyName: "partner_lead_staff_notes_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "partner_leads"
            referencedColumns: ["id"]
          },
        ]
      }
      partner_leads: {
        Row: {
          campaign_code: string | null
          consent_at: string | null
          consent_given: boolean
          converted_at: string | null
          created_at: string
          created_by: string | null
          email: string
          id: string
          interest: string | null
          name: string
          notes: string | null
          partner_id: string
          phone: string | null
          rejected_reason: string | null
          sale_id: string | null
          status: Database["public"]["Enums"]["partner_lead_status"]
          updated_at: string
        }
        Insert: {
          campaign_code?: string | null
          consent_at?: string | null
          consent_given?: boolean
          converted_at?: string | null
          created_at?: string
          created_by?: string | null
          email: string
          id?: string
          interest?: string | null
          name: string
          notes?: string | null
          partner_id: string
          phone?: string | null
          rejected_reason?: string | null
          sale_id?: string | null
          status?: Database["public"]["Enums"]["partner_lead_status"]
          updated_at?: string
        }
        Update: {
          campaign_code?: string | null
          consent_at?: string | null
          consent_given?: boolean
          converted_at?: string | null
          created_at?: string
          created_by?: string | null
          email?: string
          id?: string
          interest?: string | null
          name?: string
          notes?: string | null
          partner_id?: string
          phone?: string | null
          rejected_reason?: string | null
          sale_id?: string | null
          status?: Database["public"]["Enums"]["partner_lead_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "partner_leads_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partner_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "partner_leads_sale_id_fkey"
            columns: ["sale_id"]
            isOneToOne: false
            referencedRelation: "sales"
            referencedColumns: ["id"]
          },
        ]
      }
      partner_links: {
        Row: {
          click_count: number
          code_id: string | null
          created_at: string
          destination_path: string
          id: string
          is_active: boolean
          partner_id: string
          slug: string
          updated_at: string
          utm_campaign: string | null
          utm_medium: string | null
          utm_source: string | null
        }
        Insert: {
          click_count?: number
          code_id?: string | null
          created_at?: string
          destination_path?: string
          id?: string
          is_active?: boolean
          partner_id: string
          slug: string
          updated_at?: string
          utm_campaign?: string | null
          utm_medium?: string | null
          utm_source?: string | null
        }
        Update: {
          click_count?: number
          code_id?: string | null
          created_at?: string
          destination_path?: string
          id?: string
          is_active?: boolean
          partner_id?: string
          slug?: string
          updated_at?: string
          utm_campaign?: string | null
          utm_medium?: string | null
          utm_source?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "partner_links_code_id_fkey"
            columns: ["code_id"]
            isOneToOne: false
            referencedRelation: "partner_codes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "partner_links_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partner_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      partner_profiles: {
        Row: {
          application_id: string | null
          approved_at: string | null
          bio: string | null
          company_name: string | null
          created_at: string
          deleted_at: string | null
          display_name: string
          id: string
          is_active: boolean
          updated_at: string
          user_id: string
          website: string | null
        }
        Insert: {
          application_id?: string | null
          approved_at?: string | null
          bio?: string | null
          company_name?: string | null
          created_at?: string
          deleted_at?: string | null
          display_name: string
          id?: string
          is_active?: boolean
          updated_at?: string
          user_id: string
          website?: string | null
        }
        Update: {
          application_id?: string | null
          approved_at?: string | null
          bio?: string | null
          company_name?: string | null
          created_at?: string
          deleted_at?: string | null
          display_name?: string
          id?: string
          is_active?: boolean
          updated_at?: string
          user_id?: string
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "partner_profiles_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "partner_applications"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_events: {
        Row: {
          amount_cents: number
          created_at: string
          currency: string
          id: string
          invoice_id: string | null
          mollie_payment_id: string | null
          occurred_at: string
          order_id: string | null
          payment_id: string | null
          raw_payload: Json
          source: string
          status: Database["public"]["Enums"]["payment_status"]
        }
        Insert: {
          amount_cents: number
          created_at?: string
          currency?: string
          id?: string
          invoice_id?: string | null
          mollie_payment_id?: string | null
          occurred_at?: string
          order_id?: string | null
          payment_id?: string | null
          raw_payload?: Json
          source?: string
          status: Database["public"]["Enums"]["payment_status"]
        }
        Update: {
          amount_cents?: number
          created_at?: string
          currency?: string
          id?: string
          invoice_id?: string | null
          mollie_payment_id?: string | null
          occurred_at?: string
          order_id?: string | null
          payment_id?: string | null
          raw_payload?: Json
          source?: string
          status?: Database["public"]["Enums"]["payment_status"]
        }
        Relationships: [
          {
            foreignKeyName: "payment_events_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "invoices"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_webhook_events: {
        Row: {
          created_at: string
          error_message: string | null
          id: string
          mollie_payment_id: string | null
          payload: Json
          processed_at: string | null
          processing_status: string
          provider: string
          provider_event_id: string | null
          received_at: string
          related_webhook_event_id: string | null
          signature_valid: boolean | null
        }
        Insert: {
          created_at?: string
          error_message?: string | null
          id?: string
          mollie_payment_id?: string | null
          payload: Json
          processed_at?: string | null
          processing_status?: string
          provider?: string
          provider_event_id?: string | null
          received_at?: string
          related_webhook_event_id?: string | null
          signature_valid?: boolean | null
        }
        Update: {
          created_at?: string
          error_message?: string | null
          id?: string
          mollie_payment_id?: string | null
          payload?: Json
          processed_at?: string | null
          processing_status?: string
          provider?: string
          provider_event_id?: string | null
          received_at?: string
          related_webhook_event_id?: string | null
          signature_valid?: boolean | null
        }
        Relationships: []
      }
      payout_accounts: {
        Row: {
          account_holder_name: string
          bic: string | null
          country: string | null
          created_at: string
          deleted_at: string | null
          iban_encrypted: string
          id: string
          is_default: boolean
          partner_id: string
          updated_at: string
          verified_at: string | null
        }
        Insert: {
          account_holder_name: string
          bic?: string | null
          country?: string | null
          created_at?: string
          deleted_at?: string | null
          iban_encrypted: string
          id?: string
          is_default?: boolean
          partner_id: string
          updated_at?: string
          verified_at?: string | null
        }
        Update: {
          account_holder_name?: string
          bic?: string | null
          country?: string | null
          created_at?: string
          deleted_at?: string | null
          iban_encrypted?: string
          id?: string
          is_default?: boolean
          partner_id?: string
          updated_at?: string
          verified_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "payout_accounts_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partner_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      payout_requests: {
        Row: {
          amount_cents: number
          created_at: string
          currency: string
          id: string
          notes: string | null
          paid_at: string | null
          partner_id: string
          payout_account_id: string
          reviewed_at: string | null
          reviewed_by: string | null
          status: Database["public"]["Enums"]["payout_request_status"]
          submitted_at: string | null
          updated_at: string
        }
        Insert: {
          amount_cents: number
          created_at?: string
          currency?: string
          id?: string
          notes?: string | null
          paid_at?: string | null
          partner_id: string
          payout_account_id: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["payout_request_status"]
          submitted_at?: string | null
          updated_at?: string
        }
        Update: {
          amount_cents?: number
          created_at?: string
          currency?: string
          id?: string
          notes?: string | null
          paid_at?: string | null
          partner_id?: string
          payout_account_id?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["payout_request_status"]
          submitted_at?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "payout_requests_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partner_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payout_requests_payout_account_id_fkey"
            columns: ["payout_account_id"]
            isOneToOne: false
            referencedRelation: "payout_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          checkout_allowed_in_app: boolean
          created_at: string
          id: string
          name: string
          product_category_policy: Database["public"]["Enums"]["product_category_policy"]
          requires_manual_payment_review: boolean
          updated_at: string
        }
        Insert: {
          checkout_allowed_in_app?: boolean
          created_at?: string
          id?: string
          name: string
          product_category_policy?: Database["public"]["Enums"]["product_category_policy"]
          requires_manual_payment_review?: boolean
          updated_at?: string
        }
        Update: {
          checkout_allowed_in_app?: boolean
          created_at?: string
          id?: string
          name?: string
          product_category_policy?: Database["public"]["Enums"]["product_category_policy"]
          requires_manual_payment_review?: boolean
          updated_at?: string
        }
        Relationships: []
      }
      project_activity: {
        Row: {
          activity_type: string
          actor_id: string | null
          created_at: string
          id: string
          metadata: Json
          project_id: string
          summary: string
        }
        Insert: {
          activity_type: string
          actor_id?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          project_id: string
          summary: string
        }
        Update: {
          activity_type?: string
          actor_id?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          project_id?: string
          summary?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_activity_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_members: {
        Row: {
          created_at: string
          id: string
          invited_by: string | null
          joined_at: string
          project_id: string
          role: Database["public"]["Enums"]["project_member_role"]
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          invited_by?: string | null
          joined_at?: string
          project_id: string
          role?: Database["public"]["Enums"]["project_member_role"]
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          invited_by?: string | null
          joined_at?: string
          project_id?: string
          role?: Database["public"]["Enums"]["project_member_role"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_members_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_milestones: {
        Row: {
          completed_at: string | null
          created_at: string
          deleted_at: string | null
          description: string | null
          due_on: string | null
          id: string
          project_id: string
          sort_order: number
          title: string
          updated_at: string
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          due_on?: string | null
          id?: string
          project_id: string
          sort_order?: number
          title: string
          updated_at?: string
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          due_on?: string | null
          id?: string
          project_id?: string
          sort_order?: number
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_milestones_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_updates: {
        Row: {
          author_id: string
          body: string
          created_at: string
          deleted_at: string | null
          id: string
          is_customer_visible: boolean
          project_id: string
          title: string
          updated_at: string
        }
        Insert: {
          author_id: string
          body: string
          created_at?: string
          deleted_at?: string | null
          id?: string
          is_customer_visible?: boolean
          project_id: string
          title: string
          updated_at?: string
        }
        Update: {
          author_id?: string
          body?: string
          created_at?: string
          deleted_at?: string | null
          id?: string
          is_customer_visible?: boolean
          project_id?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_updates_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      projects: {
        Row: {
          created_at: string
          customer_user_id: string | null
          deleted_at: string | null
          description: string | null
          id: string
          metadata: Json
          order_id: string | null
          owner_staff_id: string | null
          sale_id: string | null
          starts_on: string | null
          status: Database["public"]["Enums"]["project_status"]
          target_end_on: string | null
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          customer_user_id?: string | null
          deleted_at?: string | null
          description?: string | null
          id?: string
          metadata?: Json
          order_id?: string | null
          owner_staff_id?: string | null
          sale_id?: string | null
          starts_on?: string | null
          status?: Database["public"]["Enums"]["project_status"]
          target_end_on?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          customer_user_id?: string | null
          deleted_at?: string | null
          description?: string | null
          id?: string
          metadata?: Json
          order_id?: string | null
          owner_staff_id?: string | null
          sale_id?: string | null
          starts_on?: string | null
          status?: Database["public"]["Enums"]["project_status"]
          target_end_on?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "projects_sale_id_fkey"
            columns: ["sale_id"]
            isOneToOne: false
            referencedRelation: "sales"
            referencedColumns: ["id"]
          },
        ]
      }
      push_tokens: {
        Row: {
          app_version: string | null
          created_at: string
          device_id: string | null
          id: string
          is_active: boolean
          last_seen_at: string
          platform: string
          token: string
          updated_at: string
          user_id: string
        }
        Insert: {
          app_version?: string | null
          created_at?: string
          device_id?: string | null
          id?: string
          is_active?: boolean
          last_seen_at?: string
          platform: string
          token: string
          updated_at?: string
          user_id: string
        }
        Update: {
          app_version?: string | null
          created_at?: string
          device_id?: string | null
          id?: string
          is_active?: boolean
          last_seen_at?: string
          platform?: string
          token?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      quote_acceptances: {
        Row: {
          accepted_at: string
          accepted_by: string
          created_at: string
          id: string
          ip_address: unknown
          metadata: Json
          quote_id: string
          signature_name: string
          terms_version_id: string | null
          user_agent: string | null
        }
        Insert: {
          accepted_at?: string
          accepted_by: string
          created_at?: string
          id?: string
          ip_address?: unknown
          metadata?: Json
          quote_id: string
          signature_name: string
          terms_version_id?: string | null
          user_agent?: string | null
        }
        Update: {
          accepted_at?: string
          accepted_by?: string
          created_at?: string
          id?: string
          ip_address?: unknown
          metadata?: Json
          quote_id?: string
          signature_name?: string
          terms_version_id?: string | null
          user_agent?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "quote_acceptances_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: true
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quote_acceptances_terms_version_id_fkey"
            columns: ["terms_version_id"]
            isOneToOne: false
            referencedRelation: "terms_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      quote_items: {
        Row: {
          created_at: string
          description: string
          id: string
          product_id: string | null
          quantity: number
          quote_id: string
          sort_order: number
          tax_rate_bps: number
          unit_amount_cents: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          description: string
          id?: string
          product_id?: string | null
          quantity?: number
          quote_id: string
          sort_order?: number
          tax_rate_bps?: number
          unit_amount_cents: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string
          id?: string
          product_id?: string | null
          quantity?: number
          quote_id?: string
          sort_order?: number
          tax_rate_bps?: number
          unit_amount_cents?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "quote_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quote_items_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
        ]
      }
      quotes: {
        Row: {
          created_at: string
          created_by: string | null
          currency: string
          customer_user_id: string
          deleted_at: string | null
          id: string
          notes: string | null
          project_id: string | null
          quote_number: string
          quote_request_id: string | null
          sent_at: string | null
          status: Database["public"]["Enums"]["quote_status"]
          subtotal_cents: number
          tax_cents: number
          terms_version_id: string | null
          total_cents: number
          updated_at: string
          valid_until: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          currency?: string
          customer_user_id: string
          deleted_at?: string | null
          id?: string
          notes?: string | null
          project_id?: string | null
          quote_number: string
          quote_request_id?: string | null
          sent_at?: string | null
          status?: Database["public"]["Enums"]["quote_status"]
          subtotal_cents?: number
          tax_cents?: number
          terms_version_id?: string | null
          total_cents?: number
          updated_at?: string
          valid_until?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          currency?: string
          customer_user_id?: string
          deleted_at?: string | null
          id?: string
          notes?: string | null
          project_id?: string | null
          quote_number?: string
          quote_request_id?: string | null
          sent_at?: string | null
          status?: Database["public"]["Enums"]["quote_status"]
          subtotal_cents?: number
          tax_cents?: number
          terms_version_id?: string | null
          total_cents?: number
          updated_at?: string
          valid_until?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "quotes_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_terms_version_id_fkey"
            columns: ["terms_version_id"]
            isOneToOne: false
            referencedRelation: "terms_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      reviews: {
        Row: {
          author_id: string
          body: string | null
          created_at: string
          deleted_at: string | null
          id: string
          moderated_by: string | null
          product_id: string | null
          project_id: string | null
          published_at: string | null
          rating: number
          status: Database["public"]["Enums"]["review_status"]
          title: string | null
          updated_at: string
        }
        Insert: {
          author_id: string
          body?: string | null
          created_at?: string
          deleted_at?: string | null
          id?: string
          moderated_by?: string | null
          product_id?: string | null
          project_id?: string | null
          published_at?: string | null
          rating: number
          status?: Database["public"]["Enums"]["review_status"]
          title?: string | null
          updated_at?: string
        }
        Update: {
          author_id?: string
          body?: string | null
          created_at?: string
          deleted_at?: string | null
          id?: string
          moderated_by?: string | null
          product_id?: string | null
          project_id?: string | null
          published_at?: string | null
          rating?: number
          status?: Database["public"]["Enums"]["review_status"]
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "reviews_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      sale_attributions: {
        Row: {
          attributed_at: string
          attribution_source: string
          created_at: string
          id: string
          is_primary: boolean
          partner_code_id: string | null
          partner_id: string
          partner_link_id: string | null
          sale_id: string
          updated_at: string
        }
        Insert: {
          attributed_at?: string
          attribution_source?: string
          created_at?: string
          id?: string
          is_primary?: boolean
          partner_code_id?: string | null
          partner_id: string
          partner_link_id?: string | null
          sale_id: string
          updated_at?: string
        }
        Update: {
          attributed_at?: string
          attribution_source?: string
          created_at?: string
          id?: string
          is_primary?: boolean
          partner_code_id?: string | null
          partner_id?: string
          partner_link_id?: string | null
          sale_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sale_attributions_partner_code_id_fkey"
            columns: ["partner_code_id"]
            isOneToOne: false
            referencedRelation: "partner_codes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sale_attributions_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partner_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sale_attributions_partner_link_id_fkey"
            columns: ["partner_link_id"]
            isOneToOne: false
            referencedRelation: "partner_links"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sale_attributions_sale_id_fkey"
            columns: ["sale_id"]
            isOneToOne: false
            referencedRelation: "sales"
            referencedColumns: ["id"]
          },
        ]
      }
      sales: {
        Row: {
          confirmed_by: string | null
          created_at: string
          currency: string
          customer_user_id: string | null
          deleted_at: string | null
          gross_amount_cents: number
          id: string
          metadata: Json
          net_amount_cents: number
          order_id: string | null
          partner_id: string | null
          payment_confirmed_at: string | null
          status: Database["public"]["Enums"]["sale_status"]
          updated_at: string
        }
        Insert: {
          confirmed_by?: string | null
          created_at?: string
          currency?: string
          customer_user_id?: string | null
          deleted_at?: string | null
          gross_amount_cents?: number
          id?: string
          metadata?: Json
          net_amount_cents?: number
          order_id?: string | null
          partner_id?: string | null
          payment_confirmed_at?: string | null
          status?: Database["public"]["Enums"]["sale_status"]
          updated_at?: string
        }
        Update: {
          confirmed_by?: string | null
          created_at?: string
          currency?: string
          customer_user_id?: string | null
          deleted_at?: string | null
          gross_amount_cents?: number
          id?: string
          metadata?: Json
          net_amount_cents?: number
          order_id?: string | null
          partner_id?: string | null
          payment_confirmed_at?: string | null
          status?: Database["public"]["Enums"]["sale_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sales_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partner_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      support_ticket_messages: {
        Row: {
          attachment_path: string | null
          author_id: string
          body: string
          client_message_id: string | null
          created_at: string
          deleted_at: string | null
          id: string
          is_internal: boolean
          ticket_id: string
          updated_at: string
        }
        Insert: {
          attachment_path?: string | null
          author_id: string
          body: string
          client_message_id?: string | null
          created_at?: string
          deleted_at?: string | null
          id?: string
          is_internal?: boolean
          ticket_id: string
          updated_at?: string
        }
        Update: {
          attachment_path?: string | null
          author_id?: string
          body?: string
          client_message_id?: string | null
          created_at?: string
          deleted_at?: string | null
          id?: string
          is_internal?: boolean
          ticket_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "support_ticket_messages_ticket_id_fkey"
            columns: ["ticket_id"]
            isOneToOne: false
            referencedRelation: "support_tickets"
            referencedColumns: ["id"]
          },
        ]
      }
      support_tickets: {
        Row: {
          assigned_to: string | null
          category: string | null
          closed_at: string | null
          conversation_id: string | null
          created_at: string
          deleted_at: string | null
          id: string
          priority: Database["public"]["Enums"]["support_ticket_priority"]
          project_id: string | null
          requester_id: string
          resolved_at: string | null
          status: Database["public"]["Enums"]["support_ticket_status"]
          subject: string
          updated_at: string
        }
        Insert: {
          assigned_to?: string | null
          category?: string | null
          closed_at?: string | null
          conversation_id?: string | null
          created_at?: string
          deleted_at?: string | null
          id?: string
          priority?: Database["public"]["Enums"]["support_ticket_priority"]
          project_id?: string | null
          requester_id: string
          resolved_at?: string | null
          status?: Database["public"]["Enums"]["support_ticket_status"]
          subject: string
          updated_at?: string
        }
        Update: {
          assigned_to?: string | null
          category?: string | null
          closed_at?: string | null
          conversation_id?: string | null
          created_at?: string
          deleted_at?: string | null
          id?: string
          priority?: Database["public"]["Enums"]["support_ticket_priority"]
          project_id?: string | null
          requester_id?: string
          resolved_at?: string | null
          status?: Database["public"]["Enums"]["support_ticket_status"]
          subject?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "support_tickets_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "support_tickets_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      terms_acceptances: {
        Row: {
          accepted_at: string
          context: string | null
          created_at: string
          id: string
          ip_address: unknown
          terms_version_id: string
          user_agent: string | null
          user_id: string
        }
        Insert: {
          accepted_at?: string
          context?: string | null
          created_at?: string
          id?: string
          ip_address?: unknown
          terms_version_id: string
          user_agent?: string | null
          user_id: string
        }
        Update: {
          accepted_at?: string
          context?: string | null
          created_at?: string
          id?: string
          ip_address?: unknown
          terms_version_id?: string
          user_agent?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "terms_acceptances_terms_version_id_fkey"
            columns: ["terms_version_id"]
            isOneToOne: false
            referencedRelation: "terms_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      terms_versions: {
        Row: {
          body_markdown: string
          code: string
          created_at: string
          effective_from: string
          effective_until: string | null
          id: string
          is_active: boolean
          locale: string
          title: string
          updated_at: string
          version: string
        }
        Insert: {
          body_markdown: string
          code: string
          created_at?: string
          effective_from?: string
          effective_until?: string | null
          id?: string
          is_active?: boolean
          locale?: string
          title: string
          updated_at?: string
          version: string
        }
        Update: {
          body_markdown?: string
          code?: string
          created_at?: string
          effective_from?: string
          effective_until?: string | null
          id?: string
          is_active?: boolean
          locale?: string
          title?: string
          updated_at?: string
          version?: string
        }
        Relationships: []
      }
      user_roles: {
        Row: {
          created_at: string
          granted_at: string
          granted_by: string | null
          id: string
          notes: string | null
          revoked_at: string | null
          role: Database["public"]["Enums"]["app_role"]
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          granted_at?: string
          granted_by?: string | null
          id?: string
          notes?: string | null
          revoked_at?: string | null
          role: Database["public"]["Enums"]["app_role"]
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          granted_at?: string
          granted_by?: string | null
          id?: string
          notes?: string | null
          revoked_at?: string | null
          role?: Database["public"]["Enums"]["app_role"]
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_quote: {
        Args: {
          p_confirmation?: boolean
          p_quote_id: string
          p_terms_version_id?: string
        }
        Returns: {
          created_at: string
          created_by: string | null
          currency: string
          customer_user_id: string
          deleted_at: string | null
          id: string
          notes: string | null
          project_id: string | null
          quote_number: string
          quote_request_id: string | null
          sent_at: string | null
          status: Database["public"]["Enums"]["quote_status"]
          subtotal_cents: number
          tax_cents: number
          terms_version_id: string | null
          total_cents: number
          updated_at: string
          valid_until: string | null
        }
        SetofOptions: {
          from: "*"
          to: "quotes"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      admin_assign_ticket: {
        Args: { p_assignee: string; p_ticket_id: string }
        Returns: {
          assigned_to: string | null
          category: string | null
          closed_at: string | null
          conversation_id: string | null
          created_at: string
          deleted_at: string | null
          id: string
          priority: Database["public"]["Enums"]["support_ticket_priority"]
          project_id: string | null
          requester_id: string
          resolved_at: string | null
          status: Database["public"]["Enums"]["support_ticket_status"]
          subject: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "support_tickets"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      admin_convert_lead: {
        Args: { p_lead_id: string; p_sale_id?: string }
        Returns: {
          campaign_code: string | null
          consent_at: string | null
          consent_given: boolean
          converted_at: string | null
          created_at: string
          created_by: string | null
          email: string
          id: string
          interest: string | null
          name: string
          notes: string | null
          partner_id: string
          phone: string | null
          rejected_reason: string | null
          sale_id: string | null
          status: Database["public"]["Enums"]["partner_lead_status"]
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "partner_leads"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      admin_dashboard_stats: { Args: never; Returns: Json }
      admin_qualify_lead: {
        Args: { p_lead_id: string; p_reason?: string; p_status: string }
        Returns: {
          campaign_code: string | null
          consent_at: string | null
          consent_given: boolean
          converted_at: string | null
          created_at: string
          created_by: string | null
          email: string
          id: string
          interest: string | null
          name: string
          notes: string | null
          partner_id: string
          phone: string | null
          rejected_reason: string | null
          sale_id: string | null
          status: Database["public"]["Enums"]["partner_lead_status"]
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "partner_leads"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      admin_reply_support_ticket: {
        Args: {
          p_body: string
          p_client_message_id?: string
          p_is_internal?: boolean
          p_ticket_id: string
        }
        Returns: {
          attachment_path: string | null
          author_id: string
          body: string
          client_message_id: string | null
          created_at: string
          deleted_at: string | null
          id: string
          is_internal: boolean
          ticket_id: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "support_ticket_messages"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      admin_update_ticket_status: {
        Args: {
          p_assignee?: string
          p_reason?: string
          p_status: string
          p_ticket_id: string
        }
        Returns: {
          assigned_to: string | null
          category: string | null
          closed_at: string | null
          conversation_id: string | null
          created_at: string
          deleted_at: string | null
          id: string
          priority: Database["public"]["Enums"]["support_ticket_priority"]
          project_id: string | null
          requester_id: string
          resolved_at: string | null
          status: Database["public"]["Enums"]["support_ticket_status"]
          subject: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "support_tickets"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      admin_work_queue: { Args: never; Returns: Json }
      approve_commission: {
        Args: { p_commission_id: string; p_reason: string }
        Returns: Json
      }
      approve_partner_application: {
        Args: { p_application_id: string; p_reason?: string }
        Returns: Json
      }
      book_appointment_slot: {
        Args: { p_notes?: string; p_slot_id: string; p_title: string }
        Returns: {
          cancellation_reason: string | null
          cancelled_at: string | null
          created_at: string
          customer_user_id: string
          ends_at: string
          id: string
          location: string | null
          meeting_url: string | null
          notes: string | null
          project_id: string | null
          slot_id: string | null
          staff_user_id: string | null
          starts_at: string
          status: Database["public"]["Enums"]["appointment_status"]
          timezone: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "appointments"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      can_upload_to_documents_path: {
        Args: { p_object_name: string }
        Returns: boolean
      }
      cancel_appointment: {
        Args: { p_appointment_id: string; p_reason?: string }
        Returns: {
          cancellation_reason: string | null
          cancelled_at: string | null
          created_at: string
          customer_user_id: string
          ends_at: string
          id: string
          location: string | null
          meeting_url: string | null
          notes: string | null
          project_id: string | null
          slot_id: string | null
          staff_user_id: string | null
          starts_at: string
          status: Database["public"]["Enums"]["appointment_status"]
          timezone: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "appointments"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      create_project_from_request: {
        Args: { p_project_id: string; p_status?: string }
        Returns: {
          created_at: string
          customer_user_id: string | null
          deleted_at: string | null
          description: string | null
          id: string
          metadata: Json
          order_id: string | null
          owner_staff_id: string | null
          sale_id: string | null
          starts_on: string | null
          status: Database["public"]["Enums"]["project_status"]
          target_end_on: string | null
          title: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "projects"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      current_partner_id: { Args: never; Returns: string }
      feature_flag_enabled: { Args: { p_keys: string[] }; Returns: boolean }
      has_app_role: { Args: { p_roles: string[] }; Returns: boolean }
      is_conversation_participant: {
        Args: { p_conversation_id: string }
        Returns: boolean
      }
      is_partner: { Args: never; Returns: boolean }
      is_project_member: { Args: { p_project_id: string }; Returns: boolean }
      is_staff_or_above: { Args: never; Returns: boolean }
      mark_document_scan_clean: {
        Args: { p_version_id: string }
        Returns: Json
      }
      process_payout_request: {
        Args: { p_payout_id: string; p_reason: string }
        Returns: Json
      }
      register_document_upload: {
        Args: {
          p_byte_size: number
          p_category?: string
          p_checksum_sha256?: string
          p_client_upload_id: string
          p_document_id?: string
          p_mime_type: string
          p_project_id?: string
          p_storage_path: string
          p_title: string
        }
        Returns: {
          category: string | null
          created_at: string
          current_version_id: string | null
          deleted_at: string | null
          id: string
          owner_user_id: string
          project_id: string | null
          requires_customer_approval: boolean
          status: Database["public"]["Enums"]["document_status"]
          title: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "documents"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      register_partner_lead: {
        Args: {
          p_campaign_code?: string
          p_consent_given: boolean
          p_email: string
          p_interest?: string
          p_name: string
          p_notes?: string
          p_phone?: string
        }
        Returns: {
          campaign_code: string | null
          consent_at: string | null
          consent_given: boolean
          converted_at: string | null
          created_at: string
          created_by: string | null
          email: string
          id: string
          interest: string | null
          name: string
          notes: string | null
          partner_id: string
          phone: string | null
          rejected_reason: string | null
          sale_id: string | null
          status: Database["public"]["Enums"]["partner_lead_status"]
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "partner_leads"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      reject_commission: {
        Args: { p_commission_id: string; p_reason: string }
        Returns: Json
      }
      reject_partner_application: {
        Args: { p_application_id: string; p_reason: string }
        Returns: Json
      }
      reject_payout_request: {
        Args: { p_payout_id: string; p_reason: string }
        Returns: {
          amount_cents: number
          created_at: string
          currency: string
          id: string
          notes: string | null
          paid_at: string | null
          partner_id: string
          payout_account_id: string
          reviewed_at: string | null
          reviewed_by: string | null
          status: Database["public"]["Enums"]["payout_request_status"]
          submitted_at: string | null
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "payout_requests"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      reject_quote: {
        Args: { p_quote_id: string; p_reason?: string }
        Returns: {
          created_at: string
          created_by: string | null
          currency: string
          customer_user_id: string
          deleted_at: string | null
          id: string
          notes: string | null
          project_id: string | null
          quote_number: string
          quote_request_id: string | null
          sent_at: string | null
          status: Database["public"]["Enums"]["quote_status"]
          subtotal_cents: number
          tax_cents: number
          terms_version_id: string | null
          total_cents: number
          updated_at: string
          valid_until: string | null
        }
        SetofOptions: {
          from: "*"
          to: "quotes"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      request_commission_payout: {
        Args: {
          p_amount_cents?: number
          p_commission_ids?: string[]
          p_payout_account_id?: string
        }
        Returns: {
          amount_cents: number
          created_at: string
          currency: string
          id: string
          notes: string | null
          paid_at: string | null
          partner_id: string
          payout_account_id: string
          reviewed_at: string | null
          reviewed_by: string | null
          status: Database["public"]["Enums"]["payout_request_status"]
          submitted_at: string | null
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "payout_requests"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      suspend_partner: {
        Args: { p_partner_id: string; p_reason: string }
        Returns: Json
      }
      update_partner_lead_contact: {
        Args: {
          p_interest?: string
          p_lead_id: string
          p_mark_contacted?: boolean
          p_name?: string
          p_notes?: string
          p_phone?: string
        }
        Returns: {
          campaign_code: string | null
          consent_at: string | null
          consent_given: boolean
          converted_at: string | null
          created_at: string
          created_by: string | null
          email: string
          id: string
          interest: string | null
          name: string
          notes: string | null
          partner_id: string
          phone: string | null
          rejected_reason: string | null
          sale_id: string | null
          status: Database["public"]["Enums"]["partner_lead_status"]
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "partner_leads"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      write_audit_log: {
        Args: {
          p_action: string
          p_entity_id: string
          p_entity_type: string
          p_metadata?: Json
        }
        Returns: undefined
      }
    }
    Enums: {
      account_deletion_status:
        | "requested"
        | "verified"
        | "processing"
        | "completed"
        | "rejected"
        | "cancelled"
      app_role:
        | "customer"
        | "partner_pending"
        | "partner"
        | "staff"
        | "admin"
        | "owner"
      appointment_status:
        | "requested"
        | "confirmed"
        | "rescheduled"
        | "cancelled"
        | "completed"
        | "no_show"
      commission_status:
        | "pending"
        | "awaiting_payment"
        | "payment_received"
        | "under_review"
        | "approved"
        | "payable"
        | "payout_requested"
        | "paid"
        | "rejected"
        | "reversed"
      conversation_type:
        | "customer_support"
        | "partner_support"
        | "project"
        | "direct"
      document_review_decision: "approved" | "changes_requested" | "rejected"
      document_scan_status: "pending" | "clean" | "flagged" | "failed"
      document_status:
        | "draft"
        | "uploaded"
        | "processing"
        | "available"
        | "under_review"
        | "approved"
        | "changes_requested"
        | "superseded"
        | "archived"
        | "rejected"
      invoice_status:
        | "draft"
        | "issued"
        | "partially_paid"
        | "paid"
        | "overdue"
        | "void"
        | "credited"
      notification_channel: "push" | "email" | "in_app"
      notification_delivery_status:
        | "queued"
        | "sent"
        | "delivered"
        | "failed"
        | "skipped"
      partner_application_status:
        | "draft"
        | "submitted"
        | "under_review"
        | "approved"
        | "rejected"
        | "suspended"
      partner_lead_status:
        | "new"
        | "contacted"
        | "qualified"
        | "converted"
        | "rejected"
        | "invalid"
      payment_status:
        | "created"
        | "open"
        | "pending"
        | "authorized"
        | "paid"
        | "failed"
        | "expired"
        | "canceled"
        | "refunded"
        | "partially_refunded"
        | "charged_back"
      payout_request_status:
        | "draft"
        | "submitted"
        | "under_review"
        | "approved"
        | "paid"
        | "rejected"
        | "cancelled"
      product_category_policy:
        | "service"
        | "physical_product"
        | "custom_project"
        | "digital_good"
        | "external_subscription"
        | "restricted"
        | "manual_review_required"
      project_member_role:
        | "customer"
        | "project_manager"
        | "contributor"
        | "viewer"
        | "staff"
      project_status:
        | "request_received"
        | "intake"
        | "quote"
        | "accepted"
        | "planning"
        | "in_progress"
        | "waiting_on_customer"
        | "review"
        | "revision"
        | "completed"
        | "paused"
        | "cancelled"
      quote_status:
        | "draft"
        | "sent"
        | "viewed"
        | "accepted"
        | "rejected"
        | "expired"
        | "superseded"
      review_status: "draft" | "submitted" | "published" | "hidden" | "rejected"
      sale_status:
        | "lead"
        | "qualified"
        | "quoted"
        | "won"
        | "lost"
        | "cancelled"
        | "refunded"
      support_ticket_priority: "low" | "normal" | "high" | "urgent"
      support_ticket_status:
        | "open"
        | "in_progress"
        | "waiting_on_customer"
        | "resolved"
        | "closed"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      account_deletion_status: [
        "requested",
        "verified",
        "processing",
        "completed",
        "rejected",
        "cancelled",
      ],
      app_role: [
        "customer",
        "partner_pending",
        "partner",
        "staff",
        "admin",
        "owner",
      ],
      appointment_status: [
        "requested",
        "confirmed",
        "rescheduled",
        "cancelled",
        "completed",
        "no_show",
      ],
      commission_status: [
        "pending",
        "awaiting_payment",
        "payment_received",
        "under_review",
        "approved",
        "payable",
        "payout_requested",
        "paid",
        "rejected",
        "reversed",
      ],
      conversation_type: [
        "customer_support",
        "partner_support",
        "project",
        "direct",
      ],
      document_review_decision: ["approved", "changes_requested", "rejected"],
      document_scan_status: ["pending", "clean", "flagged", "failed"],
      document_status: [
        "draft",
        "uploaded",
        "processing",
        "available",
        "under_review",
        "approved",
        "changes_requested",
        "superseded",
        "archived",
        "rejected",
      ],
      invoice_status: [
        "draft",
        "issued",
        "partially_paid",
        "paid",
        "overdue",
        "void",
        "credited",
      ],
      notification_channel: ["push", "email", "in_app"],
      notification_delivery_status: [
        "queued",
        "sent",
        "delivered",
        "failed",
        "skipped",
      ],
      partner_application_status: [
        "draft",
        "submitted",
        "under_review",
        "approved",
        "rejected",
        "suspended",
      ],
      partner_lead_status: [
        "new",
        "contacted",
        "qualified",
        "converted",
        "rejected",
        "invalid",
      ],
      payment_status: [
        "created",
        "open",
        "pending",
        "authorized",
        "paid",
        "failed",
        "expired",
        "canceled",
        "refunded",
        "partially_refunded",
        "charged_back",
      ],
      payout_request_status: [
        "draft",
        "submitted",
        "under_review",
        "approved",
        "paid",
        "rejected",
        "cancelled",
      ],
      product_category_policy: [
        "service",
        "physical_product",
        "custom_project",
        "digital_good",
        "external_subscription",
        "restricted",
        "manual_review_required",
      ],
      project_member_role: [
        "customer",
        "project_manager",
        "contributor",
        "viewer",
        "staff",
      ],
      project_status: [
        "request_received",
        "intake",
        "quote",
        "accepted",
        "planning",
        "in_progress",
        "waiting_on_customer",
        "review",
        "revision",
        "completed",
        "paused",
        "cancelled",
      ],
      quote_status: [
        "draft",
        "sent",
        "viewed",
        "accepted",
        "rejected",
        "expired",
        "superseded",
      ],
      review_status: ["draft", "submitted", "published", "hidden", "rejected"],
      sale_status: [
        "lead",
        "qualified",
        "quoted",
        "won",
        "lost",
        "cancelled",
        "refunded",
      ],
      support_ticket_priority: ["low", "normal", "high", "urgent"],
      support_ticket_status: [
        "open",
        "in_progress",
        "waiting_on_customer",
        "resolved",
        "closed",
      ],
    },
  },
} as const
